# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leap
email: saikiran.naragam@gmail.com
description: Computer Science.Technology.Impression
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://saikiran.blog" # the base hostname & protocol for your site
twitter_username: saikiran638
facebook_username:
github_username:  nsaikiran
paginate: 5


# Google services
google_analytics: UA-89879231-1


gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
