title: "Leap"
description: Computer Science. Technology. Impression
baseurl: ""
url: "http://saikiran.blog"

gems: [jekyll-paginate, kramdown,rouge]

google_analytics_id: UA-89879231-1

disqus:
  shortname: "nsaikiran"
